name: backrec_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dotted_border: ^2.0.0+2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.0
  # Remote API
  data_connection_checker_tv: ^0.3.5-nullsafety
  http: ^0.13.0
  # Local cache
  shared_preferences: ^2.0.8
  flutter_secure_storage: ^5.0.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0

  video_trimmer: ^0.6.0
  camera: ^0.9.4+14
  video_player: ^2.2.19
  file_picker: ^4.5.0
  flutter_feather_icons: ^2.0.0+1
  gallery_saver: ^2.3.2
  audio_video_progress_bar: ^0.10.0

  video_thumbnail: ^0.4.6
  flutter_typeahead: ^3.2.0
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.8

  vibration: ^1.7.4-nullsafety.0
  path_provider: ^2.0.2
  native_device_orientation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
