name: backrec_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.2.0
  flutter_bloc: ^7.3.0
  cupertino_icons: ^1.0.2
  get: ^4.2.4
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  # camerawesome: ^0.3.0+1
  camera: ^0.8.1+5
  video_player: ^2.1.12
  flutter_feather_icons: ^2.0.0+1
  flutter_typeahead: ^3.2.0
  gallery_saver: ^2.1.2
  # video_thumbnail: ^0.3.3
  audio_video_progress_bar: ^0.6.1
  image_picker: ^0.8.2
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.8
  vibration: ^1.7.4-nullsafety.0
  path_provider: ^2.0.2
  native_device_orientation: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
